exports.types = {
  "css":	"text/css",
  "html":	"text/html",
  "js":	"text/javascript",
  "txt":	"text/plain",
  "xml":	"text/xml",
  "gif":	"image/gif",
  "jpeg":	"image/jpeg",
  "jpg":	"image/jpeg",
  "png":  "image/png",
  "svg":  "image/svg+xml",
  "ico":  "image/x-icon",
  "tiff": "image/tiff",
  "json":	"application/json",
  "pdf":	"application/pdf",
  "swf":	"application/x-shockwave-flash",
  "wav":	"audio/x-wav",
  "mp3":  "audio/mp3",
  "wma":	"audio/x-ms-wma",
  "wmv":	"video/x-ms-wmv",
  "mp4":	"video/mp4"
};